---
title: "p8105_hw2_lh3109"
author: "Lesi He"
output: html_document
---


```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)

```

## Problem 1
```{r, message = FALSE}
#import Mr. Trash Wheel sheet from the excel file
mr_trash_wheel_df = 
  read_excel(
    "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
    sheet = 1,
    range = "A2:N534"
  ) %>% 
  #clean variable names
  janitor::clean_names() %>% 
  #omit rows that do not include dumpster-specific data
  filter(!is.na(dumpster)) #%>% 
  #change the variable type to integer
  #mutate(sports_balls = as.numeric(as.character(sports_balls))) %>% 
  #round the sports_balls values
  #mutate(sport_balls = round("sports_balls"))

#get median of the number of sports_balls
#sports_balls_median = median(mr_trash_wheel_df[,"sports_balls"])
mr_trash_wheel_df
#sports_balls_median

#import precipitation 2019 data
precip_2019_df = 
  read_excel(
    "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
    sheet = 6,
    range = "A2:B14"
    ) %>% 
  #clean variable names
  janitor::clean_names() %>% 
  #add year variable
  mutate(year = "2019", month = month.name[month])


#import precipitation 2018 data
precip_2018_df = 
  read_excel(
    "data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
    sheet = 7,
    range = "A2:B14"
    ) %>% 
  #clean variable names
  janitor::clean_names() %>% 
  #add year variable
  mutate(year = "2018", month = month.name[month]) 

left_join(precip_2019_df, precip_2018_df, by = "month")
```


The

The combined data set for 2018 and 2019 precipitation suggest that amount of precipitation varies a lot by each month. For instance, when there was higher amount of precipitation in January 2019, there was little precipitation in January 2018, and vice versa.

The total precipitation in 2018 is 70.33 inch. The median number of sports ball in s dumpster in 2019 is ***.


## Problem 2

```{r}

```





## Problem 3
```{r}
#read the csv file
baby_names_df = 
  read_csv("data/Popular_Baby_Names.csv", col_types = "icccii") %>% 
  #create better variable names
  janitor::clean_names() %>% 
  #remove duplicated names
  distinct() 

olivia_df = 
  #filter by the name "Olivia"
  filter(baby_names_df, childs_first_name == "Olivia") %>%
  #produce table for "Olivia" summarizing rank over years
  pivot_wider(
    ethnicity,
    names_from = "year_of_birth",
    values_from = "rank"
  ) %>% 
  knitr::kable()

popular_male_df = 
  #filter by gender
  filter(baby_names_df, gender == "MALE") %>% 
  #group the names by year
  group_by(year_of_birth) %>% 
  #extract the rows with highest counts of a name
  slice(which.max(count))


nonhis_m_2016_df = 
  #filter the dataframe by gender, year of birth and ethnicity
  filter(baby_names_df, gender == "MALE", year_of_birth == 2016, grepl("NON HISPANIC", ethnicity)) %>% 
  group_by(childs_first_name)

#create scatter plot for nonhis_male_2016_df
ggp_nonhis_m_2016 = 
  nonhis_m_2016_df %>%
    ggplot(aes(x = rank, y = count)) +
    geom_point()
  

#olivia_df
#popular_male_df
#nonhis_male_2016_df
#ggp_nonhis_m_2016
```




